version: 0.2

env:
    LOGIN: "7cf2078ee5cbdcefea96c71d3379dac3f935024e"
    HOST: "https://sonarcloud.io"
    Organization: "Hrishin0"
    Project: "Devops-Project"
phases:
  install:
    runtime-versions:
      java: corretto17  # Updated runtime version
  pre_build:
    commands:
      - yum update -y     # Equivalent to apt-get update
      - yum install -y jq # Install jq using yum package manager
      - retry_count=3
      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && break || sleep 10; done
      - tar xzf apache-maven-3.5.4-bin.tar.gz || true
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - mvn test -X
      - mvn sonar:sonar -Dsonar.login="7cf2078ee5cbdcefea96c71d3379dac3f935024e" -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey="Devops-Project"Dsonar.organization="Hrishin0" || true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey="Devops-Project" > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ]; then $CODEBUILD_BUILD_SUCCEEDING -eq 0; fi

 