version: 0.2

env:
    LOGIN: "7cf2078ee5cbdcefea96c71d3379dac3f935024e"
    HOST: "https://sonarcloud.io"
    Organization: "Hrishin0"
    Project: "Devops-Project"

phases:
  install:
    runtime-versions:
      python: 3.11
 
  pre_build:
    commands:
      - yum update -y
      - yum install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - ls
      - echo $PATH
  build:
    commands:
      - sonar-scanner -h
      # - sonar-scanner-cli-4.7.0.2747-linux -X -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.python.coverage.reportPaths=coverage.xml
      - sleep 5
      # - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=${Project} > result.json
      # - cat result.json
      # - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0; fi

artifacts:
  files:
    - '*/'